# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='draft',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Draft', 'draft'), ('Published', 'published')], default='Draft', max_length=128),
        ),
    ]
